ALTER TABLE students ADD COLUMN IF NOT EXISTS avatar_s3_key VARCHAR(255);
ALTER TABLE students ADD COLUMN IF NOT EXISTS linkedin_url VARCHAR(255);
ALTER TABLE students ADD COLUMN IF NOT EXISTS github_url VARCHAR(255);
ALTER TABLE students ADD COLUMN IF NOT EXISTS bio TEXT;
